

const projects = [{
    id: "1",
    link: "https://www.metro.de/",
    linkedin: "https://www.linkedin.com/company/metro-markets-gmbh/",
    slug: "Metro Markets Warhouse Management - METRO Markets GmbH, Germany 🇩🇪",
    title: "Metro Markets Warhouse Management - METRO Markets GmbH, Germany 🇩🇪",
    techStack: ["Odoo 17", "Python & PostgreSQL", "XML,HTML & CSS", "Git, Gitlab", "Javascript,Typescript", "Docker & Kubernates", "GCloud, GCP & CI/CD", "Odoo Telemetry & Graphana", "Rabbitmq, Lucid & Incident.io"],
    thumbnail: "/images/image_projects/metro_11.png",
    thumbnail2: "/images/image_projects/metro_22.png",
    featured: true,
}, {
    id: "2",
    link: "https://www.cellntell.com/",
    linkedin: "https://www.linkedin.com/company/mobilelive/",
    slug: "CellnTell Ecommerce Business - MobileLive, Canada 🇨🇦",
    title: "CellnTell Ecommerce Business - MobileLive, Canada 🇨🇦",
    techStack: ["Odoo 15", "Python & PostgreSQL", "XML,HTML & CSS", "Git, Gitlab", "Javascript", "Rest Api, Postman", "Jira & Notion", "Graphana", "CI/CD", "Automated Testing"],
    thumbnail: "/images/image_projects/cell_2.png",
    thumbnail2: "/images/image_projects/cell_1.png",
    featured: true,
},

    {
        id: "3",
        link: "https://www.dynexcel.com/",
        linkedin: "https://www.linkedin.com/company/dynexcel/",
        slug: "Odoo Zoom Integration - Dynexcel, Pakistan 🇵🇰", // consider renaming to "kidconnect-public-website" if this is the public-facing site
        title: "Odoo Zoom Integration - Dynexcel, Pakistan 🇵🇰",
        techStack: ["Odoo 15", "Python & PostgreSQL", "XML,HTML & CSS", "Git, Gitlab", "Javascript", "Rest Api, Postman", "Zoom"],
        thumbnail: "/images/image_projects/dynexcel_3.png",
        thumbnail2: "/images/image_projects/dynexcel_4.png",
        featured: false,

    },

    {
        id: "18",
        link: "https://gmcgypsum.com",
        linkedin: "https://www.linkedin.com/company/global-mining-co-l-l-c/",
        slug: "GLOBAL MINING COMPANY - GMC OMAN 🇴🇲",
        title: "Global Mining Company - GMC OMAN 🇴🇲",
        techStack: ["Odoo 16", "Python & PostgreSQL", "XML,HTML & CSS", "Git, Gitlab", "Javascript", "Rest Api, Postman", "Odoo PM"],
        thumbnail: "/images/image_projects/gmc_1.png",
        thumbnail2: "/images/image_projects/gmc_22.png",
        featured: true,
    },

    {
        id: "6",
        link: "https://apps.odoo.com/apps/modules/14.0/de_whatsapp_base_connector",
        linkedin: "https://www.linkedin.com/company/dynexcel/",
        slug: "Odoo Whatsapp Integration - Dynexcel, Pakistan 🇵🇰",
        title: "Odoo Whatsapp Integration - Dynexcel, Pakistan 🇵🇰",
        techStack: ["Odoo 14", "Python & PostgreSQL", "XML,HTML & CSS", "Git, Gitlab", "Javascript", "Rest Api, Postman", "Jira"],
        thumbnail: "/images/image_projects/dynexcel_5.png",
        thumbnail2: "/images/image_projects/whatsap_1.png",
        featured: false,
    },

    {
        id: "7",
        link: "https://ebizcharge.com/",
        linkedin: "https://www.linkedin.com/company/tekhqs/",
        slug: "EBizCharge Payment Gateway - TEK Headquaters, EBizCharge USA 🇺🇸",
        title: "EBizCharge Payment Gateway - TEK Headquaters, EBizCharge USA 🇺🇸",
        techStack: ["Odoo 13", "Python & PostgreSQL", "XML,HTML & CSS", "Git, Gitlab", "Javascript", "Soap Api", "Jira"],
        thumbnail: "/images/image_projects/ebiz_1.png",
        thumbnail2: "/images/image_projects/ebiz_2.png",
        featured: true,
    },

    {
        id: "12",
        link: "http://shoparty-sa.com/",
        linkedin: "https://www.linkedin.com/company/shoparty/",
        slug: "Shoparty – Odoo Implementation - Saudi Arabia 🇸🇦",
        title: "Shoparty – Odoo Implementation - Saudi Arabia 🇸🇦",
        techStack: ["Odoo 13", "Python & PostgreSQL", "XML,HTML & CSS", "Git, Gitlab", "Javascript", "Rest Api, Postman", "Odoo PM"],
        thumbnail: "/images/image_projects/shoparty_1.png",
        thumbnail2: "/images/image_projects/shoparty_2.png",
        featured: true,
    },

    {
        id: "8",
        link: "https://apps.odoo.com/apps/modules/16.0/odoo_docusign",
        linkedin: "https://www.linkedin.com/company/techloyce/",
        slug: "Odoo Docusign Connector - Techloyce, England 🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        title: "Odoo Docusign Connector - Techloyce, England 🏴󠁧󠁢󠁥󠁮󠁧󠁿󠁧󠁿",
        techStack: ["Odoo 14", "Python & PostgreSQL", "XML,HTML & CSS", "Git, Gitlab", "Javascript", "Rest Api, Postman", "Docusign"],
        thumbnail: "/images/image_projects/docusign_2.png",
        thumbnail2: "/images/image_projects/docusign_3.png",
        featured: false,
    },

    {
        id: "9",
        link: "https://www.metro.de/",
        linkedin: "https://www.linkedin.com/company/metro-markets-gmbh/",
        slug: "Microsoft Teams Integration - Dynexcel, Pakistan 🇵🇰",
        title: "Microsoft Teams Integration - Dynexcel, Pakistan 🇵🇰",
        techStack: ["Odoo 16", "Python & PostgreSQL", "XML,HTML & CSS", "Git, Gitlab", "Javascript", "Rest Api, Postman", "Microsoft Teams"],
        thumbnail: "/images/image_projects/dynexcel_3.png",
        thumbnail2: "/images/image_projects/dynexcel_4.png",
        featured: true,
    },

    {
        id: "10",
        link: "https://apps.odoo.com/apps/modules/18.0/odoo_office365",
        linkedin: "https://www.linkedin.com/company/techloyce/",
        slug: "Office 365 Integration - Techloyce, England 🏴󠁧󠁢󠁥󠁮󠁧󠁿󠁧󠁿",
        title: "Office 365 Integration - Techloyce, England 🏴󠁧󠁢󠁥󠁮󠁧󠁿󠁧󠁿",
        techStack: ["Odoo 15", "Python & PostgreSQL", "XML,HTML & CSS", "Git, Gitlab", "Javascript", "Rest Api, Postman", "Office365"],
        thumbnail: "/images/image_projects/office_1.png",
        thumbnail2: "/images/image_projects/office_2.png",
        featured: false,
    },

    {
        id: "11",
        link: "https://www.metro.de/",
        linkedin: "https://www.linkedin.com/company/metro-markets-gmbh/",
        slug: "Multi Currency Updation (Central Bank Of Myanmar) - Myanmar 🇲🇲",
        title: "Multi Currency Updation (Central Bank Of Myanmar) - Myanmar 🇲🇲",
        techStack: ["Odoo 13", "Python & PostgreSQL", "XML,HTML & CSS", "Git, Gitlab", "Javascript", "Rest Api, Postman", "Jira"],
        thumbnail: "/images/image_projects/mym_2.png",
        thumbnail2: "/images/image_projects/mym_1.png",
        featured: true,
    },

    {
        id: "13",
        link: "https://apps.odoo.com/apps/modules/16.0/shopify_connector",
        linkedin: "https://www.linkedin.com/company/techloyce/",
        slug: "Odoo Shopify Connector - Techloyce, England 🏴󠁧󠁢󠁥󠁮󠁧󠁿󠁧󠁿",
        title: "Odoo Shopify Connector - Techloyce, England 🏴󠁧󠁢󠁥󠁮󠁧󠁿󠁧󠁿",
        techStack: ["Odoo 16", "Python & PostgreSQL", "XML,HTML & CSS", "Git, Gitlab", "Javascript", "Rest Api, Postman", "Shopify"],
        thumbnail: "/images/image_projects/techloyce_1.png",
        thumbnail2: "/images/image_projects/techloyce_2.png",
        featured: true,
    }, {
        id: "14",
        link: "https://apps.odoo.com/apps/modules/16.0/odoo%20mailchimp",
        linkedin: "https://www.linkedin.com/company/techloyce/",
        slug: "Odoo MailChimp Connector - Techloyce, England 🏴󠁧󠁢󠁥󠁮󠁧󠁿󠁧󠁿",
        title: "Odoo MailChimp Connector - Techloyce, England 🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        techStack: ["Odoo 15", "Python & PostgreSQL", "XML,HTML & CSS", "Git, Gitlab", "Javascript", "Rest Api, Postman", "MailChimp"],
        thumbnail: "/images/image_projects/mailchimp_3.png",
        thumbnail2: "/images/image_projects/mailchimp_2.png",
        featured: false,
    }, {
        id: "15",
        link: "https://apps.odoo.com/apps/modules/18.0/sharepoint_odoo_connector",
        linkedin: "https://apps.odoo.com/apps/modules/16.0/sharepoint_odoo_connector",
        slug: "Odoo SharePoint Integration - Techloyce, England 🏴󠁧󠁢󠁥󠁮󠁧󠁿󠁿",
        title: "Odoo SharePoint Integration - Techloyce, England 🏴󠁧󠁢󠁥󠁮󠁧󠁿󠁧󠁿",
        techStack: ["Odoo 13", "Python & PostgreSQL", "XML,HTML & CSS", "Git, Gitlab", "Javascript", "Rest Api, Postman", "SharePoint"],
        thumbnail: "/images/image_projects/sp_1.png",
        thumbnail2: "/images/image_projects/sp_2.png",
        featured: false,
    }, {
        id: "16",
        link: "https://www.metro.de/",
        linkedin: "https://www.linkedin.com/company/metro-markets-gmbh/",
        slug: "Odoo Slack Integration - Dynexcel, Pakistan 🇵🇰",
        title: "Odoo Slack Integration - Dynexcel, Pakistan 🇵🇰",
        techStack: ["Odoo 12", "Python & PostgreSQL", "XML,HTML & CSS", "Git, Gitlab", "Javascript", "Rest Api, Postman", "Slack"],
        thumbnail: "/images/image_projects/dynexcel_6.png",
        thumbnail2: "/images/image_projects/dynexcel_4.png",
        featured: true,
    }, {
        id: "17",
        link: "https://apps.odoo.com/apps/modules/browse/page/2?order=Relevance&author=Techloyce",
        linkedin: "https://www.linkedin.com/company/techloyce/",
        slug: "Odoo WooCommerce Integration - Techloyce, England 🏴󠁧󠁢󠁥󠁮󠁧󠁿󠁧󠁿",
        title: "Odoo WooCommerce Integration - Techloyce, England 🏴󠁧󠁢󠁥󠁮󠁧󠁿󠁧󠁿",
        techStack: ["Odoo 16", "Python & PostgreSQL", "XML,HTML & CSS", "Git, Gitlab", "Javascript", "Rest Api, Postman", "WooCommerce"],
        thumbnail: "/images/image_projects/techloyce_3.png",
        thumbnail2: "/images/image_projects/techloyce_4.png",
        featured: true,
    },

    {
        id: "19",
        link: "https://apps.odoo.com/apps/modules/18.0/box_integration",
        linkedin: "https://www.linkedin.com/company/techloyce/",
        slug: "Odoo Box Integration - Techloyce, England 🏴󠁧󠁢󠁥󠁮󠁧󠁿󠁢󠁥󠁮󠁧󠁧󠁿",
        title: "Odoo Box Integration -Techloyce, England 🏴󠁧󠁢󠁥󠁮󠁧󠁿󠁢󠁥󠁮󠁧󠁧󠁿󠁧󠁢󠁥󠁮󠁧",
        techStack: ["Odoo 12", "Python & PostgreSQL", "XML,HTML & CSS", "Git, Gitlab", "Javascript", "Rest Api, Postman", "Box"],
        thumbnail: "/images/image_projects/box_1.png",
        thumbnail2: "/images/image_projects/box_2.png",
        featured: false,
    }, {
        id: "20",
        link: "https://apps.odoo.com/apps/modules/16.0/dropbox_connector_odoo",
        linkedin: "https://www.linkedin.com/company/techloyce/",
        slug: "Odoo DropBox Integration - Techloyce, England 🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        title: "Odoo DropBox Integration - Techloyce, England 🏴󠁧󠁢󠁥󠁮󠁧󠁿󠁧󠁢󠁥󠁮󠁧",
        techStack: ["Odoo 13", "Python & PostgreSQL", "XML,HTML & CSS", "Git, Gitlab", "Javascript", "Rest Api, Postman", "DropBox"],
        thumbnail: "/images/image_projects/dp_1.png",
        thumbnail2: "/images/image_projects/dp_2.png",
        featured: false,
    },


];
export default projects;